[project]
name = "action_soso"
authors = [{name = "Leon Dionne", email = "ldionne@dridesign.sh.cn"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
	"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
	"Development Status :: 5 - Production/Stable",
	"Environment :: X11 Applications :: Gnome",
	"Intended Audience :: End Users/Desktop",
	"Operating System :: POSIX",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.13",
	"Topic :: Desktop Environment",
	"Topic :: Desktop Environment :: File Managers",
	"Topic :: Desktop Environment :: Gnome",
	"Topic :: Utilities"
]
keywords = [
	"nemo", "nemo actions",
	"file manager", "file manager actions",
	"change case", "change case files",
	"date files", "backup", "backup files",
	"resize files"
]
dynamic = ["version", "description"]
dependencies = ["zenity_soso"]

[project.urls]
Home = "https://github.com/Zen-Master-SoSo/action_soso"

[project.scripts]
action-soso = "action_soso.__main__:main"
change-case-files = "action_soso.change_case_files:main"
copy-content = "action_soso.copy_content:main"
date-filename = "action_soso.date_filename:main"
number-files = "action_soso.number_files:main"
resize-files = "action_soso.resize_files:main"
gen-nemo-launcher = "action_soso.gen_nemo_launcher:main"
tag-filenames = "action_soso.tag_filenames:main"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[bumpver]
current_version = "1.4.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = false
push = false

[bumpver.file_patterns]
"action_soso/__init__.py" = [
    '^__version__ = "{version}"$',
]
